/*
Author: Erick Kamamba 
Twitter: @ErickKamamba
Created On: 1/26/2021
Updated On: 1/27/2021
Description: This SQL inserts Databases and tables
*/

USE [master]
GO

/****** Object:  Database [SmartData]    Script Date: 1/26/2021 9:23:26 PM ******/
CREATE DATABASE [SmartData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmartData', FILENAME = N'G:\Data\SmartData.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SmartData_log', FILENAME = N'Z:\Logs\SmartData_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SmartData] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmartData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SmartData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmartData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmartData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmartData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmartData] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmartData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SmartData] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SmartData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmartData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmartData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmartData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmartData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmartData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmartData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmartData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmartData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmartData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmartData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmartData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmartData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmartData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmartData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmartData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmartData] SET RECOVERY FULL 
GO

ALTER DATABASE [SmartData] SET  MULTI_USER 
GO

ALTER DATABASE [SmartData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmartData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmartData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmartData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SmartData] SET  READ_WRITE 
GO


CREATE TABLE [dbo].[Students](
	[StudentID] [int] IDENTITY(1,1) NOT NULL,
	[StudentName] [varchar](50) NULL,
	[StudentNumber] [varchar](50) NULL,
	[BirthDate] [date] NULL,
	[Gender] [varchar](6) NULL,
	[Height] [int] NULL,
	[Nationality] [varchar](50) NULL,
	[Race] [varchar](50) NULL,
	[City] [varchar](20) NULL,
	[State] [char](2) NULL,
	[ZipCode] [varchar](10) NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [varchar](50) NULL,
 CONSTRAINT [PK_Students] PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Courses](
	[CourseID] [int] IDENTITY(1,1) NOT NULL,
	[CourseName] [varchar](50) NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [varchar](50) NULL,
 CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED 
(
	[CourseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE [dbo].[Courses] ADD  CONSTRAINT [DF_Courses_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO

CREATE TABLE [dbo].[Hobbies](
	[HobbyID] [int] IDENTITY(1,1) NOT NULL,
	[Hobby] [varchar](50) NULL,
 CONSTRAINT [PK_Hobbies] PRIMARY KEY CLUSTERED 
(
	[HobbyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[StudentHobbies](
	[StudentID] [int] NULL,
	[HobbyID] [int] NULL
) ON [PRIMARY]

GO


